version: '2'

services:
  # redis:
  #   image: redis:alpine
  #   container_name: redis
  #   ports:
  #     - "6379:6379"
  #   command: redis-server --appendonly yes
  #   volumes:
  #     - redisData: /data
  mysql:
    image: mysql:5.7
    container_name: mysql
    command: mysqld --user=root
    volumes:
      - mysqlData:/var/lib/mysql
      - ~/dump:/dump
    environment:
      - MYSQL_DATABASE=projectName-test
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
  app:
    image: "139.59.84.83:5000/scoring:0.9"
    container_name: scoring
    environment:
      - NODE_ENV=test

    depends_on:
      - mysql
      # - redis
    command: pm2 start --name "projectName" --no-daemon index.js

    # Expose ports [HOST:CONTAINER}
    ports:
      - "4040:4040"
volumes:
  mysqlData:
  # redisData:
